#ifndef APPLICATIONDEFINITIONS_H__
#define APPLICATIONDEFINITIONS_H__

enum {
  	SEND_INTERVAL_MS = 250,
  	MAX_ANCHOR = 4,
  	BUFFER_DEPTH = 10,
  	STEP_SIZE = 1,
  	CALC_POS_INTERVAL_MS = 2000
};

#endif //APPLICATIONDEFINITIONS_H__