#ifndef APPLICATIONDEFINITIONS_H__
#define APPLICATIONDEFINITIONS_H__

enum {
  SEND_INTERVAL_MS = 250,
  ANCHOR_ID = 4,
  COORDINATE_X = 0,
  COORDINATE_Y = 10
};

#endif //APPLICATIONDEFINITIONS_H__